version: "3"
services:
  authd:
    build:
      context: .
      dockerfile: ./cmd/authd/Dockerfile
    platform: linux/amd64
    environment:
      - AUTH_LOG_DEBUG=true
      - AUTH_LOG_JSON=true
      - AUTH_RPC_ADDR=:5000
      - AUTH_NEAR_ADDR=neard:5000
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    depends_on:
      - neard
    restart: unless-stopped
  neard:
    build:
      context: .
      dockerfile: ./cmd/neard/Dockerfile
    platform: linux/amd64
    environment:
      - NEAR_LOG_DEBUG=true
      - NEAR_LOG_JSON=true
      - NEAR_RPC_ADDR=:5000
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    restart: unless-stopped
  storaged:
    build:
      context: .
      dockerfile: ./cmd/storaged/Dockerfile
    platform: linux/amd64
    environment:
      - STORAGE_LOG_DEBUG=true
      - STORAGE_LOG_JSON=true
      - STORAGE_HTTP_ADDR=:8888
      - STORAGE_UPLOADER_IPFS_MULTIADDR=/dns4/ipfs/tcp/5001
      - STORAGE_BROKER_ADDR=brokerd:5000
      - STORAGE_AUTH_ADDR=authd:5000
      - STORAGE_SKIP_AUTH=false
    ports:
      - "127.0.0.1:8888:8888"
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    depends_on:
      - brokerd
      - authd
    restart: unless-stopped
  auctioneerd:
    build:
      context: .
      dockerfile: ./cmd/auctioneerd/Dockerfile
    platform: linux/amd64
    volumes:
      - "${REPO_PATH}/auctioneerd:/data/auctioneerd"
    environment:
      - AUCTIONEER_LOG_DEBUG=true
      - AUCTIONEER_LOG_JSON=true
      - AUCTIONEER_RPC_ADDR=:5000
      - AUCTIONEER_MONGO_URI=mongodb://mongo:27017
      - AUCTIONEER_MONGO_DBNAME=auctioneerd
      - AUCTIONEER_BROKER_ADDR=brokerd:5000
      - AUCTIONEER_AUCTION_DURATION=10000000000
      - AUCTIONEER_AUCTION_ATTEMPTS=10
      - AUCTIONEER_PRIVATE_KEY=mCAESQIBDTKg1bP0wk8H59cK+TgnN9ZzncDw3XWZFbWciALxrUOpAO/2xCE7cCgXzQLB7tncMoWbBW3UytRkDEWg0bYw
      - AUCTIONEER_MDNS=true
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    depends_on:
      - brokerd
    restart: unless-stopped
  bidbot:
    build:
      context: .
      dockerfile: ./cmd/bidbot/Dockerfile
    platform: linux/amd64
    volumes:
      - "${REPO_PATH}/bidbot:/data/bidbot"
    environment:
      - BIDBOT_LOG_DEBUG=true
      - BIDBOT_LOG_JSON=true
      - BIDBOT_WALLET_ADDR=f1u44svaac2dzqbgbbizwutibq6lsud2qzcnedxuq
      - BIDBOT_WALLET_ADDR_SIG=018a51c263a12985ae176f9bde1460f32f72a8fb5ed004497dc0a5424a9f4dbc917ea80e0b4dd4f138027a07117ecf6cf26389be102521adf719090d69c4b6a54f01
      - BIDBOT_ASK_PRICE=100000000000
      - BIDBOT_VERIFIED_ASK_PRICE=100000000000
      - BIDBOT_FAST_RETRIEVAL=false
      - BIDBOT_DEAL_START_WINDOW=2880
      - BIDBOT_DEAL_DURATION_MIN=525600
      - BIDBOT_DEAL_DURATION_MAX=1051200
      - BIDBOT_DEAL_SIZE_MIN=57344
      - BIDBOT_DEAL_SIZE_MAX=32000000000
      - BIDBOT_PRIVATE_KEY=mCAESQMTvC9vrfZGa8g9q5oSJM1VbcU5OnYa/PdXuzte77jsft8HAmDRgV6Gw1QVWGSOG8v/LmhO0b2kEVgnux1Y8Hgk
      - BIDBOT_MDNS=true
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    restart: unless-stopped
  brokerd:
    build:
      context: .
      dockerfile: ./cmd/brokerd/Dockerfile
    platform: linux/amd64
    environment:
      - BROKER_LOG_DEBUG=true
      - BROKER_LOG_JSON=true
      - BROKER_RPC_ADDR=:5000
      - BROKER_MONGO_URI=mongodb://mongo:27017
      - BROKER_MONGO_DBNAME=brokerd
      - BROKER_IPFS_MULTIADDR=/dns4/ipfs/tcp/5001
      - BROKER_PACKER_ADDR=packerd:5000
      - BROKER_AUCTIONEER_ADDR=auctioneerd:5000
      - BROKER_DEALER_ADDR=dealerd:5000
      - BROKER_REPORTER_ADDR=neard:5000
      - BROKER_DEAL_DURATION=1051200
      - BROKER_VERIFIED_DEALS=true
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    depends_on:
      - packerd
      - mongo
      - ipfs
    restart: unless-stopped
  packerd:
    build:
      context: .
      dockerfile: ./cmd/packerd/Dockerfile
    platform: linux/amd64
    environment:
      - PACKER_LOG_DEBUG=true
      - PACKER_LOG_JSON=true
      - PACKER_RPC_ADDR=:5000
      - PACKER_MONGO_URI=mongodb://mongo:27017
      - PACKER_MONGO_DBNAME=packerd
      - PACKER_IPFS_MULTIADDR=/dns4/ipfs/tcp/5001
      - PACKER_BROKER_ADDR=brokerd:5000
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    depends_on:
      - mongo
      - ipfs
    restart: unless-stopped
  dealerd:
    build:
      context: .
      dockerfile: ./cmd/dealerd/Dockerfile
    platform: linux/amd64
    environment:
      - DEALER_LOG_DEBUG=true
      - DEALER_LOG_JSON=true
      - DEALER_RPC_ADDR=:5000
      - DEALER_MONGO_URI=mongodb://mongo:27017
      - DEALER_MONGO_DBNAME=dealerd
      - DEALER_BROKER_ADDR=brokerd:5000
      - DEALER_MOCK=true
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    depends_on:
      - brokerd
    restart: unless-stopped
  mongo:
    image: mongo:latest
    platform: linux/amd64
    ports:
      - "127.0.0.1:27017:27017"
    logging:
      driver: none
    command:
      - /bin/bash
      - -c
      - |
        /usr/bin/mongod --fork --logpath /var/log/mongod.log --bind_ip_all --replSet rs0
        mongo --eval 'rs.initiate({_id: "rs0", version: 1, members: [{ _id: 0, host: "mongo:27017" }]})'
        tail -f /var/log/mongod.log
  ipfs:
    image: ipfs/go-ipfs:v0.8.0
    platform: linux/amd64
    environment:
      - IPFS_PROFILE=test
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "127.0.0.1:5001:5001"
      - "127.0.0.1:8080:8080"
