version: "3"
services:
  storaged:
    build:
      context: .
      dockerfile: ./cmd/storaged/Dockerfile
    environment:
      - STORAGE_LOG_DEBUG=true
      - STORAGE_HTTP_LISTEN_ADDR=:8888
      - STORAGE_UPLOADER_IPFS_MULTIADDR=/dns4/ipfs/tcp/5001
      - STORAGE_BROKER_ADDR=brokerd:5000
    ports:
      - "127.0.0.1:8888:8888"
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    depends_on:
      - brokerd
  brokerd:
    build:
      context: .
      dockerfile: ./cmd/brokerd/Dockerfile
    environment:
      - BROKER_LOG_DEBUG=true
      - BROKER_GRPC_LISTEN_ADDR=:5000
      - BROKER_MONGO_URI=mongodb://mongo:27017
      - BROKER_MONGO_DBNAME=brokerd
    ports:
      - "127.0.0.1:5000:5000"
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"
    command:
      - /bin/bash
      - -c
      - |
        /usr/bin/mongod --fork --logpath /var/log/mongod.log --bind_ip_all --replSet rs0
        mongo --eval 'rs.initiate({_id: "rs0", version: 1, members: [{ _id: 0, host: "mongo:27017" }]})'
        tail -f /var/log/mongod.log
  ipfs:
    image: ipfs/go-ipfs:v0.8.0
    environment:
      - IPFS_PROFILE=test
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "127.0.0.1:5001:5001"
      - "127.0.0.1:8080:8080"
