apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auctioneer-01
  labels:
    app: auctioneer
spec:
  serviceName: auctioneer
  replicas: 2
  selector:
    matchLabels:
      app: auctioneer-v1
  template:
    metadata:
      labels:
        app: auctioneer-v1
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000
        fsGroup: 2000
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: configure-auctioneer
          image: ubuntu:latest
          imagePullPolicy: IfNotPresent
          command:
            - bash
            - "-c"
            - |
              set -ex
              ls /env
              [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
              ordinal=${BASH_REMATCH[1]}
              cp /env/configAuctioneer$ordinal.env /data/auctioneerd/.env
          volumeMounts:
            - name: auctioneer-store
              mountPath: /data/auctioneerd
            - name: configure-env
              mountPath: /env
      containers:
        - name: auctioneer
          image: textile/auctioneer
          imagePullPolicy: Always
          ports:
            - name: api
              containerPort: 5000
            - name: metrics
              containerPort: 9090
          volumeMounts:
            - name: auctioneer-store
              mountPath: /data/auctioneerd
          resources:
            requests:
              memory: 4Gi
              cpu: "2"
            limits:
              memory: 6Gi
      volumes:
        - name: configure-env
          configMap:
            name: configmap-auctioneer
  volumeClaimTemplates:
    - metadata:
        name: auctioneer-store
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi
