apiVersion: batch/v1
kind: Job
metadata:
  name: uploadbot
  namespace: broker-<ENV>
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: uploadbot
    spec:
      restartPolicy: OnFailure
      containers:
        - name: uploadbot
          image: "node:16-buster"
          env:
            - name: COUNT
              value: "1000000000"
            - name: MIN_SIZE
              value: "1000"
            - name: MAX_SIZE
              value: "100000"
            - name: ENDPOINT
              value: "http://storage:8888"
            - name: SLEEP
              value: "1"
            - name: SEED_PHRASE
              value: "height unusual narrow dream follow grow rebel panda because then equip basic"
          command:
            - /bin/bash
            - -c
            - |
              set -x
              npm install -g near-cli
              wget -O bench.sh https://gist.githubusercontent.com/jsign/e1b7e72aa27c15958b28780e80bad67a/raw/72c33bf70329f1a04ba9da1a9a009094be5979e9/bench.sh
              chmod 755 bench.sh
              ./bench.sh $ENDPOINT $MIN_SIZE $MAX_SIZE $COUNT $SLEEP
