apiVersion: v1
kind: ConfigMap
metadata:
  name: ipfs-cluster-set-bootstrap-conf
data:
  addresses-announce-0: '["/ip4/FIXME/tcp/4001"]'
  addresses-announce-1: '["/ip4/FIXME/tcp/4001"]'
  addresses-announce-2: '["/ip4/FIXME/tcp/4001"]'
  addresses-announce-3: '["/ip4/FIXME/tcp/4001"]'