apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: broker-production

resources:
- ../base
- ../base/ipfs-cluster
- cert.yaml
- mongo-cluster-rolebinding.yaml

configMapGenerator:
- files:
  - configAuctioneer0.env
  - configAuctioneer1.env
  name: configmap-auctioneer
- envs:
  - configAuth.env
  name: configmap-auth
- envs:
  - configBroker.env
  name: configmap-broker
- envs:
  - configDealer.env
  name: configmap-dealer
- envs:
  - configNear.env
  name: configmap-near
- envs:
  - configPacker.env
  name: configmap-packer
- envs:
  - configPiecer.env
  name: configmap-piecer
- envs:
  - configStorage.env
  name: configmap-storage
- envs:
  - configIpfsCluster.env
  name: ipfs-cluster-env-config

patchesStrategicMerge:
- ipfs-cluster-volumeclaim-patch.yaml
- ipfs-cluster-statefulset-patch.yaml
- ingress-patch.yaml
- mongo-patch.yaml
- dealerd-patch.yaml
- neard-patch.yaml
- piecer-patch.yaml
- storaged-patch.yaml
