apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      role: mongo
      environment: production
  template:
    metadata:
      labels:
        role: mongo
        environment: production
    spec:
      containers:
        - name: mongo-sidecar
          image: morphy/k8s-mongo-sidecar:0.5.1
          env:
            - name: KUBERNETES_POD_LABELS
              value: "role=mongo,environment=production"
            - name: KUBERNETES_SERVICE_NAME
              value: "mongo"
