apiVersion: v1
kind: ConfigMap
metadata:
  name: config-01
data:
  # Auctioneer
  AUCTIONEER_LOG_DEBUG: "true"
  AUCTIONEER_LOG_JSON: "true"
  AUCTIONEER_RPC_ADDR: ":5000"
  AUCTIONEER_MONGO_URI: "mongodb://mongo-0.mongo.broker-staging.svc.cluster.local,mongo-1.mongo.broker-staging.svc.cluster.local,mongo-2.mongo.broker-staging.svc.cluster.local:27017/?replicaSet=rs0"
  AUCTIONEER_MONGO_DBNAME: "auctioneerd"
  AUCTIONEER_BROKER_ADDR: "broker:5000"
  AUCTIONEER_AUCTION_DURATION: "10000000000"
  AUCTIONEER_LISTEN_MULTIADDR: "/ip4/0.0.0.0/tcp/4001,/ip4/0.0.0.0/udp/4001/quic"
  AUCTIONEER_ANNOUNCE_MULTIADDR: "/ip4/34.83.24.156/tcp/4001,/ip4/34.83.24.156/udp/4001/quic"
  AUCTIONEER_PRIVATE_KEY: "mCAESQGVQtjDNgoM80czVoyqa4uQqDk+2dcvezuyGWZuTztjW6/9OR5IJue2qhVFd3y+wB1iuVppAodNdIlY4Bmk0350"
  AUCTIONEER_QUIC: "true"
  # Auth
  AUTH_LOG_DEBUG: "true"
  AUTH_LOG_JSON: "true"
  AUTH_RPC_ADDR: ":5000"
  AUTH_NEAR_ADDR: "near:5000"
  # Broker
  BROKER_LOG_DEBUG: "true"
  BROKER_LOG_JSON: "true"
  BROKER_RPC_ADDR: ":5000"
  BROKER_MONGO_URI: "mongodb://mongo-0.mongo.broker-staging.svc.cluster.local,mongo-1.mongo.broker-staging.svc.cluster.local,mongo-2.mongo.broker-staging.svc.cluster.local:27017/?replicaSet=rs0"
  BROKER_MONGO_DBNAME: "brokerd"
  BROKER_IPFS_MULTIADDR: "/dns4/ipfs/tcp/5001"
  BROKER_PACKER_ADDR: "packer:5000"
  BROKER_AUCTIONEER_ADDR: "auctioneer:5000"
  BROKER_DEALER_ADDR: "dealer:5000"
  BROKER_REPORTER_ADDR: "near:5000"
  BROKER_DEAL_EPOCHS: "1051200"
  # Dealer
  DEALER_LOG_DEBUG: "true"
  DEALER_LOG_JSON: "true"
  DEALER_RPC_ADDR: ":5000"
  DEALER_MONGO_URI: "mongodb://mongo-0.mongo.broker-staging.svc.cluster.local,mongo-1.mongo.broker-staging.svc.cluster.local,mongo-2.mongo.broker-staging.svc.cluster.local:27017/?replicaSet=rs0"
  DEALER_MONGO_DBNAME: "dealerd"
  DEALER_BROKER_ADDR: "broker:5000"
  DEALER_MOCK: "true"
  # Near
  NEAR_LOG_DEBUG: "true"
  NEAR_LOG_JSON: "true"
  NEAR_RPC_ADDR: ":5000"
  # Packer
  PACKER_LOG_DEBUG: "true"
  PACKER_LOG_JSON: "true"
  PACKER_RPC_ADDR: ":5000"
  PACKER_MONGO_URI: "mongodb://mongo-0.mongo.broker-staging.svc.cluster.local,mongo-1.mongo.broker-staging.svc.cluster.local,mongo-2.mongo.broker-staging.svc.cluster.local:27017/?replicaSet=rs0"
  PACKER_MONGO_DBNAME: "packerd"
  PACKER_IPFS_MULTIADDR: "/dns4/ipfs/tcp/5001"
  PACKER_BROKER_ADDR: "broker:5000"
  # Storage
  STORAGE_LOG_DEBUG: "true"
  STORAGE_LOG_JSON: "true"
  STORAGE_HTTP_ADDR: ":8888"
  STORAGE_UPLOADER_IPFS_MULTIADDR: "/dns4/ipfs/tcp/5001"
  STORAGE_BROKER_ADDR: "broker:5000"
  STORAGE_AUTH_ADDR: "auth:5000"
