apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-01
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: broker
          env:
            - name: BROKER_GPUBSUB_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: gpubsub-project-id
            - name: BROKER_GPUBSUB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: gpubsub-api-key
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.17
          command:
            - "/cloud_sql_proxy"
            - "-instances=textile-310716:us-west1:broker-edge=tcp:5432"
          resources:
            requests:
              memory: "10Mi"
              cpu:    "0.1"

