apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ipfs-cluster
spec:
  volumeClaimTemplates:
    - metadata:
        name: cluster-storage
      spec:
        storageClassName: balanced-ipfs-cluster
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: ipfs-storage
      spec:
        storageClassName: premium-ipfs-cluster
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Gi
