apiVersion: v1
kind: ConfigMap
metadata:
  name: ipfs-cluster-set-bootstrap-conf
data:
  addresses-announce-0: '["/ip4/34.105.35.95/tcp/4001"]'
  addresses-announce-1: '["/ip4/35.247.120.20/tcp/4001"]'