apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ipfs-cluster-pdb
spec:
  minAvailable: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ipfs-cluster
spec:
  replicas: 2

