apiVersion: v1
kind: Service
metadata:
  name: ipfs-cluster-swarm-0
spec:
  externalTrafficPolicy: Local
  selector:
    app: ipfs-cluster
    statefulset.kubernetes.io/pod-name: ipfs-cluster-0
  ports:
    - name: swarm
      targetPort: swarm
      port: 4001
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: ipfs-cluster-swarm-1
spec:
  externalTrafficPolicy: Local
  selector:
    app: ipfs-cluster
    statefulset.kubernetes.io/pod-name: ipfs-cluster-1
  ports:
    - name: swarm
      targetPort: swarm
      port: 4001
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: ipfs-cluster-swarm-2
spec:
  externalTrafficPolicy: Local
  selector:
    app: ipfs-cluster
    statefulset.kubernetes.io/pod-name: ipfs-cluster-2
  ports:
    - name: swarm
      targetPort: swarm
      port: 4001
  type: LoadBalancer
