apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ipfs-cluster
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: ipfs
          resources:
            requests:
              memory: 4Gi
              cpu: "2"
            limits:
              memory: 16Gi
              cpu: "4"


