apiVersion: v1
kind: ConfigMap
metadata:
  name: ipfs-cluster-set-bootstrap-conf
data:
  addresses-announce-0: '["/ip4/34.83.36.118/tcp/4001"]'
  addresses-announce-1: '["/ip4/34.82.221.249/tcp/4001"]'
  addresses-announce-2: '["/ip4/34.83.88.62/tcp/4001"]'