apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: broker-staging

resources:
- ../base
- ../base/ipfs-cluster
- cert.yaml
- ipfs-cluster-service.yaml
- mongo-cluster-rolebinding.yaml

configMapGenerator:
- files:
  - configAuctioneer0.env
  - configAuctioneer1.env
  name: configmap-auctioneer
- envs:
  - configAuth.env
  name: configmap-auth
- envs:
  - configBroker.env
  name: configmap-broker
- envs:
  - configDealer.env
  name: configmap-dealer
- envs:
  - configNear.env
  name: configmap-near
- envs:
  - configEth.env
  name: configmap-eth
- envs:
  - configPoly.env
  name: configmap-poly
- envs:
  - configPacker.env
  name: configmap-packer
- envs:
  - configPiecer.env
  name: configmap-piecer
- envs:
  - configStorage.env
  name: configmap-storage
- envs:
  - configIpfsCluster.env
  name: ipfs-cluster-env-config

secretGenerator:
- files:
  - secret/cluster-secret
  - secret/bootstrap-peer-priv-key
  name: ipfs-cluster-secret-config
  type: Opaque

patchesStrategicMerge:
- auctioneer-pdb.yaml
- auth-pdb.yaml
- broker-pdb.yaml
- dealer-pdb.yaml
- eth-pdb.yaml
- near-pdb.yaml
- packer-pdb.yaml
- piecer-pdb.yaml
- poly-pdb.yaml
- storage-pdb.yaml
- ipfs-cluster-setup-confmap-patch.yaml
- ipfs-cluster-volumeclaim-patch.yaml
- ipfs-cluster-statefulset-patch.yaml
- ingress-patch.yaml
- mongo-patch.yaml
- storaged-patch.yaml
- brokerd-patch.yaml
- dealerd-patch.yaml
- piecerd-patch.yaml
- packerd-patch.yaml
- authd-patch.yaml

