apiVersion: apps/v1
kind: Deployment
metadata:
  name: packer-01
spec:
  template:
    spec:
      containers:
        - name: packer
          env:
            - name: PACKER_GPUBSUB_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: gpubsub-project-id
            - name: PACKER_GPUBSUB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: gpubsub-api-key
